#SPDX-License-Identifier: MIT-0
---
- name: Install dconf
  ansible.builtin.apt:
    name: dconf-cli
    state: present

- name: Apply settings
  community.general.dconf:
    key: "{{ name }}"
    value: "{{ value }}"
  loop: "{{ settings }}"